update 1
mswitas/project-js-group-2 pull request #26
Opened 2023-12-22 22:24 UTC by Lukasz8791

Wydaje mi się, że jest w miarę, po świętach popracuję nad szczegółami. I Kinga pobierze mi obrazek, którego aktualnie zastąpiłem amazonem :D

2023-12-22 23:43 UTC, mswitas requested changes
Zrób merge z aktualnym mainem, konfliktów brak ale pewne rzeczy mogą się rozapść.

2023-12-22 23:43 UTC, mswitas commented on package.json
Niepokoją mnie te zmiany w package.json, nie ma takiej potrzeby a może się coś rozpaść sprawdź to a najlepiej zmerguj sobie ze świeżym mainem.

2023-12-22 23:43 UTC, mswitas commented on src/partials/sidebar_categories_support.html
wycinasz tu menu-categories dodane wcześniej prze Małgorzatę

2023-12-27 20:11 UTC, Lukasz8791 commented
add support Ukraine partial section

2023-12-27 20:26 UTC, Lukasz8791 commented on src/partials/sidebar_categories_support.html
poprawione

2023-12-27 20:27 UTC, Lukasz8791 commented on package.json
świeżo zmerdzowany main

2023-12-27 20:32 UTC, closed without merging